name: Test
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint JS-Files
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3

      - name: Setup node
        uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236 # v3.1.0
        with:
          node-version: 16

      - run: npm install

      - name: Lint
        run: npm run lint

  test:
    needs:
      - lint
    runs-on: ubuntu-latest
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3

      - name: Setup node
        uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236 # v3.1.0
        with:
          node-version: 16
          
      - run: npm install
      - run: npm test